version: '3'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile_php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: ubid

  mysql:
    build:
      context: .
      dockerfile: dockerfile_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./ubid.sql:/docker-entrypoint-initdb.d/ubid.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ubid
